In [1]:
%pip install scikit_learn

   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.1 MB 2.1 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/11.1 MB 2.4 MB/s eta 0:00:05
   ------ --------------------------------- 1.8/11.1 MB 2.4 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.1 MB 2.6 MB/s eta 0:00:04
   ------------ --------------------------- 3.4/11.1 MB 3.0 MB/s eta 0:00:03
   --------------- ------------------------ 4.2/11.1 MB 3.1 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.1 MB 3.2 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.1 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.1 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 7.3/11.1 MB 3.4 MB/s eta 0:00:02
   ------------------------------ --------- 8.4/11.1 MB 3.5 MB/s eta 0:00:01
   ----------


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import pandas as pd

In [10]:
import numpy as np

In [8]:
df=pd.read_csv("Ice Cream.csv")
df

Temperature  Revenue
0           24.6      535
1           26.1      626
2           27.8      661
3           20.6      488
4           11.6      317
..           ...      ...
495         22.3      525
496         32.9      756
497         12.6      307
498         22.4      567
499         29.0      656

[500 rows x 2 columns]

In [9]:
from sklearn.linear_model import LinearRegression

In [13]:
model=LinearRegression()
X=df[['Temperature']]
y=df[['Revenue']]
model.fit(X,y)

LinearRegression()

In [14]:
model.predict([[70]])

c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[1545.23406814]])

In [20]:
df=pd.read_csv("Ice Cream Sales - temperatures.csv")
df

Temperature  Ice Cream Profits
0             39              13.17
1             40              11.88
2             41              18.82
3             42              18.65
4             43              17.02
..           ...                ...
360           99              85.13
361           99              87.08
362           99              89.29
363          101              81.91
364          101              85.02

[365 rows x 2 columns]

In [16]:
from sklearn.linear_model import LinearRegression

In [21]:
model=LinearRegression()
X=df[['Temperature']]
y=df[['Ice Cream Profits']]
model.fit(X,y)

LinearRegression()

In [22]:
np.random.seed(19)
temps=np.random.randint(25,100,8)
temps=np.sort(temps,kind='mergesort')
temps

array([44, 47, 56, 65, 77, 81, 91, 99], dtype=int32)

In [24]:
sales_pred=pd.DataFrame({"Temperature":temps})
sales_pred

Temperature
0           44
1           47
2           56
3           65
4           77
5           81
6           91
7           99

In [25]:
results = model.predict(sales_pred[['Temperature']])
results

array([[18.75022687],
       [22.32625366],
       [33.05433402],
       [43.78241438],
       [58.08652153],
       [62.85455724],
       [74.77464653],
       [84.31071797]])